// src/views/AdminView.tsx
import { useEffect, useState } from 'react'
import type { ColumnsType } from 'antd/es/table'
import {
  Button,
  Card,
  Checkbox,
  Input,
  Modal,
  Select,
  Table,
  Tag,
  Typography,
  Upload,
} from 'antd'
import { selectIsAdmin, selectIsSuperAdmin, selectUsername, useAuthStore } from '@/stores/auth'
import {
  allUsers as allUsersApi,
  approveUser as approveUserApi,
  changeRole as changeRoleApi,
  deleteUser as deleteUserApi,
  type PendingUser,
  pendingUsers as pendingUsersApi,
  rejectUser as rejectUserApi,
} from '@/api/users'
import {
  addUnit as addUnitApi,
  deleteUnit as deleteUnitApi,
  importUnits as importUnitsApi,
  listUnits as listUnitsApi,
} from '@/api/units'
import { publishAnnouncement as publishAnnouncementApi } from '@/api/logs'
import { formatTime, roleLabel, roleTagColor } from '@/utils'
import { usePasswordModal } from '@/composables/usePasswordModal'
import type { SysUser, UsageUnit } from '@/types'
import { getErrorMessage, isHandledError } from '@/api/request'
import { messageError, messageSuccess } from '@/utils/messageBridge'
import { appConfirm } from '@/utils/antdAppBridge'
import AppIcon from '@/components/AppIcon'
import './AdminView.css'

const { Text } = Typography

const roleOptions = [
  { label: '普通用户', value: 'ROLE_USER' },
  { label: '管理员', value: 'ROLE_ADMIN' },
  { label: '超级管理员', value: 'ROLE_SUPER_ADMIN' },
]

export default function AdminView() {
  const isAdmin = useAuthStore(selectIsAdmin)
  const isSuperAdmin = useAuthStore(selectIsSuperAdmin)
  const currentUsername = useAuthStore(selectUsername)
  const openPasswordModal = usePasswordModal((s) => s.open)

  const [pendingList, setPendingList] = useState<PendingUser[]>([])
  const [allUsersList, setAllUsersList] = useState<SysUser[]>([])
  const [pendingLoading, setPendingLoading] = useState(false)
  const [usersLoading, setUsersLoading] = useState(false)

  const [roleTarget, setRoleTarget] = useState<SysUser | null>(null)
  const [roleValue, setRoleValue] = useState('')
  const [roleSubmitting, setRoleSubmitting] = useState(false)

  const [showAnnounceModal, setShowAnnounceModal] = useState(false)
  const [announceContent, setAnnounceContent] = useState('')
  const [announcePinned, setAnnouncePinned] = useState(false)
  const [announcePublishing, setAnnouncePublishing] = useState(false)

  // 使用单位（获取页下拉数据源）
  const [unitsList, setUnitsList] = useState<UsageUnit[]>([])
  const [unitsLoading, setUnitsLoading] = useState(false)
  const [newUnitName, setNewUnitName] = useState('')
  const [addingUnit, setAddingUnit] = useState(false)
  const [importingUnits, setImportingUnits] = useState(false)

  async function loadPending() {
    setPendingLoading(true)
    try {
      setPendingList(await pendingUsersApi())
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setPendingLoading(false)
    }
  }

  async function loadAllUsers() {
    setUsersLoading(true)
    try {
      setAllUsersList(await allUsersApi())
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setUsersLoading(false)
    }
  }

  async function loadUnits() {
    setUnitsLoading(true)
    try {
      setUnitsList(await listUnitsApi())
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setUnitsLoading(false)
    }
  }

  useEffect(() => {
    void loadPending()
    void loadAllUsers()
    void loadUnits()
  }, [])

  function doApprove(id: number) {
    appConfirm({
      title: '审核通过',
      content: '确定要通过该用户的注册申请吗？',
      onOk: async () => {
        try {
          await approveUserApi(id)
          messageSuccess('已通过审核')
          await Promise.all([loadPending(), loadAllUsers()])
        } catch (err) {
          if (!isHandledError(err)) messageError(getErrorMessage(err))
        }
      },
    })
  }

  function doReject(id: number) {
    appConfirm({
      title: '拒绝注册',
      content: '确定要拒绝该用户的注册申请吗？',
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await rejectUserApi(id)
          messageSuccess('已拒绝')
          await loadPending()
        } catch (err) {
          if (!isHandledError(err)) messageError(getErrorMessage(err))
        }
      },
    })
  }

  function openRoleModal(u: SysUser) {
    setRoleTarget(u)
    setRoleValue(u.role)
  }

  async function submitRoleChange() {
    if (!roleTarget) return
    if (roleValue === roleTarget.role) {
      setRoleTarget(null)
      return
    }
    setRoleSubmitting(true)
    try {
      await changeRoleApi(roleTarget.id, roleValue)
      messageSuccess(`角色已更新为「${roleLabel(roleValue)}」`)
      setRoleTarget(null)
      await loadAllUsers()
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setRoleSubmitting(false)
    }
  }

  function confirmDeleteUser(u: SysUser) {
    appConfirm({
      title: '删除用户确认',
      content: (
        <div>
          确定要删除用户 <strong>{u.username}</strong> 吗？此操作不可恢复。
        </div>
      ),
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await deleteUserApi(u.id)
          messageSuccess('用户已删除')
          await Promise.all([loadPending(), loadAllUsers()])
        } catch (err) {
          if (!isHandledError(err)) messageError(getErrorMessage(err))
        }
      },
    })
  }

  function openAnnounceModal() {
    setAnnounceContent('')
    setAnnouncePinned(false)
    setShowAnnounceModal(true)
  }

  async function publishAnnouncement() {
    if (!announceContent.trim()) {
      messageError('请输入公告内容')
      return
    }
    setAnnouncePublishing(true)
    try {
      await publishAnnouncementApi(announceContent, announcePinned)
      messageSuccess('公告已发布')
      setShowAnnounceModal(false)
      setAnnounceContent('')
      setAnnouncePinned(false)
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setAnnouncePublishing(false)
    }
  }

  /* ===== 使用单位 ===== */

  /** 手动添加使用单位 */
  async function doAddUnit() {
    const name = newUnitName.trim()
    if (!name) {
      messageError('请输入单位名称')
      return
    }
    setAddingUnit(true)
    try {
      await addUnitApi(name)
      messageSuccess(`已添加单位「${name}」`)
      setNewUnitName('')
      await loadUnits()
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setAddingUnit(false)
    }
  }

  /** 文件批量导入使用单位（.txt/.csv 每行一个；.xlsx 取第一列） */
  async function doImportUnits(file: File) {
    setImportingUnits(true)
    try {
      const result = await importUnitsApi(file)
      messageSuccess(`导入完成，共导入 ${result.imported} 个使用单位`)
      await loadUnits()
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setImportingUnits(false)
    }
  }

  function confirmDeleteUnit(u: UsageUnit) {
    appConfirm({
      title: '删除使用单位',
      content: `确定要删除单位「${u.name}」吗？删除后获取页下拉将不再显示该单位，已写入激活码备注的历史记录不受影响。`,
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await deleteUnitApi(u.id)
          messageSuccess('单位已删除')
          await loadUnits()
        } catch (err) {
          if (!isHandledError(err)) messageError(getErrorMessage(err))
        }
      },
    })
  }

  const pendingColumns: ColumnsType<PendingUser> = [
    {
      title: '用户名',
      render: (_: unknown, row: PendingUser) => <Text strong>{row.username}</Text>,
    },
    {
      title: '注册时间',
      width: 180,
      render: (_: unknown, row: PendingUser) => <Text type="secondary">{formatTime(row.createTime)}</Text>,
    },
    {
      title: '操作',
      width: 200,
      render: (_: unknown, row: PendingUser) => (
        <div style={{ display: 'flex', gap: 8 }}>
          <Button size="small" onClick={() => doApprove(row.id)}>
            通过
          </Button>
          <Button size="small" type="default" danger onClick={() => doReject(row.id)}>
            拒绝
          </Button>
        </div>
      ),
    },
  ]

  const userColumns: ColumnsType<SysUser> = [
    { title: '#', width: 60, dataIndex: 'id' },
    {
      title: '用户名',
      render: (_: unknown, row: SysUser) => <Text strong>{row.username}</Text>,
    },
    {
      title: '角色',
      width: 160,
      render: (_: unknown, row: SysUser) => <Tag color={roleTagColor(row.role)}>{roleLabel(row.role)}</Tag>,
    },
    {
      title: '状态',
      width: 110,
      render: (_: unknown, row: SysUser) =>
        row.approved ? <Tag color="green">已审核</Tag> : <Tag color="gold">待审</Tag>,
    },
    {
      title: '注册时间',
      width: 180,
      render: (_: unknown, row: SysUser) => <Text type="secondary">{formatTime(row.createTime)}</Text>,
    },
    {
      title: '操作',
      width: 300,
      render: (_: unknown, row: SysUser) => (
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {isAdmin && (
            <Button size="small" type="default" onClick={() => openPasswordModal(row)}>
              改密
            </Button>
          )}
          {isSuperAdmin && (
            <Button
              size="small"
              type="default"
              disabled={row.username === currentUsername || row.role === 'ROLE_SUPER_ADMIN'}
              onClick={() => openRoleModal(row)}
            >
              改角色
            </Button>
          )}
          {isSuperAdmin && row.username !== currentUsername ? (
            <Button
              size="small"
              type="default"
              danger
              onClick={() => confirmDeleteUser(row)}
            >
              删除
            </Button>
          ) : isSuperAdmin ? (
            <span style={{ display: 'inline-block', width: 56 }} />
          ) : null}
        </div>
      ),
    },
  ]

  const unitColumns: ColumnsType<UsageUnit> = [
    { title: '#', width: 60, dataIndex: 'id' },
    {
      title: '单位名称',
      render: (_: unknown, row: UsageUnit) => <Text strong>{row.name}</Text>,
    },
    {
      title: '创建时间',
      width: 180,
      render: (_: unknown, row: UsageUnit) => <Text type="secondary">{formatTime(row.createTime)}</Text>,
    },
    {
      title: '操作',
      width: 100,
      render: (_: unknown, row: UsageUnit) => (
        <Button size="small" type="default" danger onClick={() => confirmDeleteUnit(row)}>
          删除
        </Button>
      ),
    },
  ]

  return (
    <div>
      <div className="page-header-block">
        <h2 className="page-title">系统管理</h2>
        <p className="page-subtitle">用户审核、角色管理、使用单位与系统公告</p>
      </div>

      {pendingList.length > 0 && (
        <Card
          className="table-card"
          styles={{ body: { padding: 24 } }}
          variant="outlined"
          style={{ marginBottom: 16 }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <Tag color="red">{pendingList.length}</Tag>
            <Text strong className="card-title">
              待审核用户
            </Text>
          </div>
          <Table<PendingUser>
            rowKey="id"
            columns={pendingColumns}
            dataSource={pendingList}
            loading={pendingLoading}
            bordered
            scroll={{ x: 560 }}
            pagination={false}
          />
        </Card>
      )}

      <Card className="table-card" styles={{ body: { padding: 24 } }} variant="outlined">
        <div style={{ marginBottom: 12 }}>
          <Text strong className="card-title">
            用户管理
          </Text>
        </div>
        <Table<SysUser>
          rowKey="id"
          columns={userColumns}
          dataSource={allUsersList}
          loading={usersLoading}
          bordered
          scroll={{ x: 1000 }}
          pagination={false}
        />
      </Card>

      {/* 瀑布流区：使用单位 + 系统公告（宽屏两列按内容高度排布，窄屏单列堆叠） */}
      <div className="admin-masonry">
        {/* 使用单位：手动添加 + 文件批量导入，供获取页下拉读取 */}
        <Card className="table-card" styles={{ body: { padding: 24 } }} variant="outlined">
          <div className="units-header">
            <Text strong className="card-title">
              使用单位
            </Text>
            <div className="units-actions">
              <Input
                className="units-add-input"
                value={newUnitName}
                onChange={(e) => setNewUnitName(e.target.value)}
                onPressEnter={() => void doAddUnit()}
                placeholder="输入单位名称，回车或点击添加"
                maxLength={100}
                disabled={addingUnit}
              />
              <Button
                type="primary"
                loading={addingUnit}
                disabled={!newUnitName.trim()}
                onClick={() => void doAddUnit()}
              >
                添加
              </Button>
              <Upload
                accept=".txt,.csv,.xlsx"
                showUploadList={false}
                disabled={importingUnits}
                beforeUpload={(file) => {
                  void doImportUnits(file)
                  return false
                }}
              >
                <Button icon={<AppIcon name="upload" size={14} />} loading={importingUnits}>
                  批量导入
                </Button>
              </Upload>
            </div>
          </div>
          <Text type="secondary" className="units-hint">
            维护「获取激活码」页面可选的使用单位；申领时选中单位将写入该激活码的备注字段。
            批量导入支持 .txt / .csv（每行一个单位）/ .xlsx（第一列）。
          </Text>
          <Table<UsageUnit>
            rowKey="id"
            columns={unitColumns}
            dataSource={unitsList}
            loading={unitsLoading}
            bordered
            scroll={{ x: 560 }}
            pagination={unitsList.length > 10 ? { pageSize: 10, size: 'small' } : false}
            style={{ marginTop: 16 }}
          />
        </Card>

        {/* 系统公告：发布公告入口独立成卡片，与用户管理模块解耦 */}
        <Card className="table-card" styles={{ body: { padding: 24 } }} variant="outlined">
          <div className="announce-header">
            <Text strong className="card-title">
              系统公告
            </Text>
            <Button type="primary" icon={<AppIcon name="notification" size={14} />} onClick={openAnnounceModal}>
              发布公告
            </Button>
          </div>
          <Text type="secondary">
            公告发布后将展示在所有用户的「获取」页面顶部；勾选「置顶」的公告会优先显示。
          </Text>
        </Card>
      </div>

      {/* 修改角色 */}
      <Modal
        open={!!roleTarget}
        onCancel={() => setRoleTarget(null)}
        title="修改角色"
        footer={null}
        width={420}
        closable
        maskClosable={false}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Text type="secondary">
            为用户 <Text strong style={{ color: '#1e293b' }}>{roleTarget?.username}</Text> 选择新角色：
          </Text>
          <Select
            value={roleValue || undefined}
            onChange={(v) => setRoleValue(v as string)}
            options={roleOptions}
            placeholder="请选择角色"
            size="large"
          />
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12, marginTop: 24 }}>
          <Button onClick={() => setRoleTarget(null)}>取消</Button>
          <Button
            type="primary"
            loading={roleSubmitting}
            disabled={!roleValue}
            onClick={() => void submitRoleChange()}
          >
            {roleSubmitting ? '提交中...' : '确认修改'}
          </Button>
        </div>
      </Modal>

      {/* 发布公告 */}
      <Modal
        open={showAnnounceModal}
        onCancel={() => setShowAnnounceModal(false)}
        title="发布公告"
        footer={null}
        width={520}
        closable
        maskClosable={false}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Input.TextArea
            value={announceContent}
            onChange={(e) => setAnnounceContent(e.target.value)}
            maxLength={500}
            autoSize={{ minRows: 4, maxRows: 8 }}
            placeholder="请输入公告内容..."
          />
          <Checkbox checked={announcePinned} onChange={(e) => setAnnouncePinned(e.target.checked)}>
            置顶此公告
          </Checkbox>
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12, marginTop: 24 }}>
          <Button onClick={() => setShowAnnounceModal(false)}>取消</Button>
          <Button
            type="primary"
            loading={announcePublishing}
            disabled={!announceContent.trim()}
            onClick={() => void publishAnnouncement()}
          >
            {announcePublishing ? '发布中...' : '发布'}
          </Button>
        </div>
      </Modal>
    </div>
  )
}

// src/views/AdminView.vue
<script setup lang="ts">
import { h, ref, onMounted, type VNode } from 'vue'
import { NButton, NTag, NSelect, useDialog, type DataTableColumns } from 'naive-ui'
import { useAuthStore } from '@/stores/auth'
import {
  approveUser as approveUserApi,
  rejectUser as rejectUserApi,
  changeRole as changeRoleApi,
  deleteUser as deleteUserApi,
  allUsers as allUsersApi,
  pendingUsers as pendingUsersApi,
  type PendingUser,
} from '@/api/users'
import { publishAnnouncement as publishAnnouncementApi } from '@/api/logs'
import { useUtils } from '@/composables/useUtils'
import { usePasswordModal } from '@/composables/usePasswordModal'
import type { SysUser } from '@/types'
import { getErrorMessage, isHandledError } from '@/api/request'

const auth = useAuthStore()
const { message, formatTime, roleLabel, roleTagType } = useUtils()
const { open: openPasswordModal } = usePasswordModal()
const dialog = useDialog()

/* ===== 状态 ===== */
const pendingList = ref<PendingUser[]>([])
const allUsersList = ref<SysUser[]>([])
const pendingLoading = ref(false)
const usersLoading = ref(false)

const showDeleteModal = ref(false)
const deleteTarget = ref<SysUser | null>(null)

const showAnnounceModal = ref(false)
const announceContent = ref('')
const announcePinned = ref(false)
const announcePublishing = ref(false)

/* ===== 待审核用户列 ===== */
const pendingColumns: DataTableColumns<PendingUser> = [
  {
    title: '用户名',
    key: 'username',
    minWidth: 180,
    render: (row) => h('strong', { style: 'color:#1e293b;' }, row.username),
  },
  {
    title: '注册时间',
    key: 'createTime',
    width: 180,
    render: (row) =>
      h('span', { style: 'color:#64748b; font-size:13px;' }, formatTime(row.createTime)),
  },
  {
    title: '操作',
    key: 'actions',
    width: 200,
    align: 'center' as const,
    render: (row) =>
      h('div', { style: 'display:flex; gap:8px; justify-content:center;' }, [
        h(
          NButton,
          {
            size: 'small',
            type: 'success',
            style: 'min-width:56px;',
            onClick: () => doApprove(row.id),
          },
          { default: () => '通过' },
        ),
        h(
          NButton,
          {
            size: 'small',
            type: 'error',
            style: 'min-width:56px;',
            onClick: () => doReject(row.id),
          },
          { default: () => '拒绝' },
        ),
      ]),
  },
]

/* ===== 全部用户列 ===== */
const usersColumns: DataTableColumns<SysUser> = [
  { title: '#', key: 'id', width: 60 },
  {
    title: '用户名',
    key: 'username',
    minWidth: 150,
    render: (row) => h('strong', { style: 'color:#1e293b;' }, row.username),
  },
  {
    title: '角色',
    key: 'role',
    width: 160,
    render: (row) => {
      if (canChangeRole(row)) {
        const options = [
          { label: '普通用户', value: 'ROLE_USER' },
          { label: '管理员', value: 'ROLE_ADMIN' },
        ]
        if (auth.isSuperAdmin) {
          options.push({ label: '超级管理员', value: 'ROLE_SUPER_ADMIN' })
        }
        return h(NSelect, {
          value: row.role,
          size: 'small',
          style: 'width: 140px;',
          options,
          'onUpdate:value': (v: string | number | null) => changeUserRole(row.id, v as string),
        })
      }
      return h(
        NTag,
        { type: roleTagType(row.role), size: 'small', round: true },
        { default: () => roleLabel(row.role) },
      )
    },
  },
  {
    title: '状态',
    key: 'approved',
    width: 110,
    render: (row) =>
      h(
        NTag,
        { type: row.approved ? 'success' : 'warning', size: 'small', round: true },
        { default: () => (row.approved ? '已审核' : '待审') },
      ),
  },
  {
    title: '注册时间',
    key: 'createTime',
    width: 180,
    render: (row) =>
      h(
        'span',
        { style: 'color:#64748b; font-size:13px; white-space:nowrap;' },
        formatTime(row.createTime),
      ),
  },
  {
    title: '操作',
    key: 'actions',
    width: 220,
    align: 'center' as const,
    render: (row) => {
      const btns: VNode[] = []
      if (auth.isAdmin) {
        btns.push(
          h(
            NButton,
            { size: 'small', style: 'min-width:56px;', onClick: () => openPasswordModal(row) },
            { default: () => '改密' },
          ),
        )
      }
      if (auth.isSuperAdmin && row.username !== auth.username) {
        btns.push(
          h(
            NButton,
            {
              size: 'small',
              type: 'error',
              style: 'min-width:56px;',
              onClick: () => confirmDeleteUser(row),
            },
            { default: () => '删除' },
          ),
        )
      } else if (auth.isSuperAdmin) {
        // 占位，保持按钮位置对齐
        btns.push(h('span', { style: 'display:inline-block; width:56px;' }))
      }
      return h('div', { style: 'display:flex; gap:6px; justify-content:center;' }, btns)
    },
  },
]

/* ===== 角色变更权限 ===== */
function canChangeRole(u: SysUser): boolean {
  return auth.isAdmin && (u.role !== 'ROLE_SUPER_ADMIN' || auth.isSuperAdmin)
}

/* ===== 数据加载 ===== */
async function loadPending() {
  pendingLoading.value = true
  try {
    pendingList.value = await pendingUsersApi()
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    pendingLoading.value = false
  }
}

async function loadAllUsers() {
  usersLoading.value = true
  try {
    allUsersList.value = await allUsersApi()
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    usersLoading.value = false
  }
}

/* ===== 审核操作 ===== */
function doApprove(id: number) {
  dialog.success({
    title: '审核通过',
    content: '确定要通过该用户的注册申请吗？',
    positiveText: '通过',
    negativeText: '取消',
    onPositiveClick: async () => {
      try {
        await approveUserApi(id)
        message.success('已通过审核')
        await Promise.all([loadPending(), loadAllUsers()])
      } catch (err) {
        if (!isHandledError(err)) message.error(getErrorMessage(err))
      }
    },
  })
}

function doReject(id: number) {
  dialog.warning({
    title: '拒绝注册',
    content: '确定要拒绝该用户的注册申请吗？',
    positiveText: '拒绝',
    negativeText: '取消',
    onPositiveClick: async () => {
      try {
        await rejectUserApi(id)
        message.success('已拒绝')
        await loadPending()
      } catch (err) {
        if (!isHandledError(err)) message.error(getErrorMessage(err))
      }
    },
  })
}

/* ===== 角色变更 ===== */
async function changeUserRole(id: number, role: string) {
  try {
    await changeRoleApi(id, role)
    message.success('角色已更新')
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    await loadAllUsers()
  }
}

/* ===== 删除用户 ===== */
function confirmDeleteUser(u: SysUser) {
  deleteTarget.value = u
  showDeleteModal.value = true
}

async function doDeleteUser() {
  const target = deleteTarget.value
  if (!target) return
  try {
    await deleteUserApi(target.id)
    message.success('用户已删除')
    showDeleteModal.value = false
    deleteTarget.value = null
    await Promise.all([loadPending(), loadAllUsers()])
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  }
}

/* ===== 发布公告 ===== */
function openAnnounceModal() {
  announceContent.value = ''
  announcePinned.value = false
  showAnnounceModal.value = true
}

async function publishAnnouncement() {
  if (!announceContent.value.trim()) {
    message.warning('请输入公告内容')
    return
  }
  announcePublishing.value = true
  try {
    await publishAnnouncementApi(announceContent.value, announcePinned.value)
    message.success('公告已发布')
    showAnnounceModal.value = false
    announceContent.value = ''
    announcePinned.value = false
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    announcePublishing.value = false
  }
}

onMounted(() => {
  loadPending()
  loadAllUsers()
})
</script>

<template>
  <div>
    <!-- 页头 -->
    <div class="page-header-block">
      <n-space align="center" justify="space-between" wrap>
        <div>
          <h2 class="page-title">用户管理</h2>
          <p class="page-subtitle">审核注册、角色管理、系统公告</p>
        </div>
        <n-button type="primary" @click="openAnnounceModal">发布公告</n-button>
      </n-space>
    </div>

    <!-- 待审核用户 -->
    <n-card
      v-if="pendingList.length"
      :bordered="false"
      class="table-card"
      style="margin-bottom: 24px"
    >
      <template #header>
        <n-badge :value="pendingList.length" :max="99" type="error">
          <span class="card-title">待审核用户</span>
        </n-badge>
      </template>
      <n-data-table
        :columns="pendingColumns"
        :data="pendingList"
        :loading="pendingLoading"
        :bordered="false"
        :single-line="false"
        :scroll-x="560"
      />
    </n-card>

    <!-- 全部用户 -->
    <n-card :bordered="false" class="table-card">
      <template #header>
        <span class="card-title">全部用户</span>
      </template>
      <n-data-table
        :columns="usersColumns"
        :data="allUsersList"
        :loading="usersLoading"
        :bordered="false"
        :single-line="false"
        :scroll-x="900"
      />
    </n-card>

    <!-- 删除用户确认 -->
    <n-modal v-model:show="showDeleteModal" preset="dialog" type="error" :show-icon="true">
      <template #header>删除用户确认</template>
      <div>
        确定要删除用户 <strong>{{ deleteTarget?.username }}</strong> 吗？此操作不可恢复。
      </div>
      <template #action>
        <n-button size="medium" @click="showDeleteModal = false">取消</n-button>
        <n-button size="medium" type="error" @click="doDeleteUser">确认删除</n-button>
      </template>
    </n-modal>

    <!-- 发布公告 -->
    <n-modal
      v-model:show="showAnnounceModal"
      preset="card"
      style="max-width: min(520px, 92vw)"
      :mask-closable="false"
    >
      <template #header>发布公告</template>
      <n-space vertical :size="16">
        <n-input
          v-model:value="announceContent"
          type="textarea"
          :maxlength="500"
          show-count
          :autosize="{ minRows: 4, maxRows: 8 }"
          placeholder="请输入公告内容..."
        />
        <n-checkbox v-model:checked="announcePinned">置顶此公告</n-checkbox>
      </n-space>
      <template #footer>
        <n-space justify="end">
          <n-button @click="showAnnounceModal = false">取消</n-button>
          <n-button
            type="primary"
            :loading="announcePublishing"
            :disabled="!announceContent.trim()"
            @click="publishAnnouncement"
          >
            {{ announcePublishing ? '发布中...' : '发布' }}
          </n-button>
        </n-space>
      </template>
    </n-modal>
  </div>
</template>

<style scoped>
.table-card {
  border-radius: 14px;
}
.card-title {
  font-size: 16px;
  font-weight: 700;
  color: #0f172a;
}

/* ===== 移动端适配 ===== */
@media (max-width: 768px) {
  .table-card {
    border-radius: 16px;
  }
  .card-title {
    font-size: 15px;
  }
}
</style>
