// src/views/LogsView.vue
<script setup lang="ts">
import { h, ref, reactive, onMounted } from 'vue'
import { NTag, type DataTableColumns } from 'naive-ui'
import { logs } from '@/api/logs'
import { useUtils } from '@/composables/useUtils'
import { getErrorMessage, isHandledError } from '@/api/request'
import type { OperationLog } from '@/types'

const { message, formatTime, actionLabel, actionTagType } = useUtils()

const logList = ref<OperationLog[]>([])
const loading = ref(false)
const logPage = ref(1)
const logSize = ref(20)

const columns: DataTableColumns<OperationLog> = [
  { title: '#', key: 'id', width: 70 },
  {
    title: '操作人',
    key: 'username',
    width: 130,
    render: (row: OperationLog) => h('strong', { style: 'color:#1e293b;' }, row.username),
  },
  {
    title: '操作',
    key: 'action',
    width: 140,
    render: (row: OperationLog) =>
      h(
        NTag,
        { type: actionTagType(row.action), size: 'small', round: true },
        { default: () => actionLabel(row.action) },
      ),
  },
  {
    title: '对象',
    key: 'target',
    minWidth: 200,
    render: (row: OperationLog) =>
      row.target
        ? h('span', { class: 'code-chip' }, row.target)
        : h('span', { style: 'color:#94a3b8;' }, '—'),
  },
  {
    title: '详情',
    key: 'detail',
    minWidth: 180,
    render: (row: OperationLog) =>
      h('span', { style: 'color:#64748b; font-size:13px;' }, row.detail || '—'),
  },
  {
    title: '时间',
    key: 'createTime',
    width: 170,
    render: (row: OperationLog) =>
      h(
        'span',
        { style: 'color:#64748b; font-size:13px; white-space:nowrap;' },
        formatTime(row.createTime),
      ),
  },
]

async function loadLogs(page: number) {
  loading.value = true
  try {
    const data = await logs(page, logSize.value)
    logList.value = data.logs
    logPage.value = page
    pagination.page = page
    pagination.itemCount = data.totalElements
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    loading.value = false
  }
}

const pagination = reactive({
  page: 1,
  pageSize: 20,
  showSizePicker: true,
  pageSizes: [10, 20, 50, 100],
  itemCount: 0,
  onUpdatePage: (page: number) => loadLogs(page),
  onUpdatePageSize: (pageSize: number) => {
    logSize.value = pageSize
    loadLogs(1)
  },
})

onMounted(() => loadLogs(1))
</script>

<template>
  <div>
    <div class="page-header-block">
      <h2 class="page-title">操作日志</h2>
      <p class="page-subtitle">系统操作审计记录</p>
    </div>

    <n-card :bordered="false" class="table-card">
      <n-spin :show="loading">
        <n-data-table
          remote
          :columns="columns"
          :data="logList"
          :pagination="pagination"
          :bordered="false"
          :single-line="false"
          :scroll-x="1000"
        />
      </n-spin>
    </n-card>
  </div>
</template>

<style scoped>
.table-card {
  border-radius: 18px;
  overflow: hidden;
  background: var(--lg-bg) !important;
  backdrop-filter: blur(24px) saturate(200%);
  -webkit-backdrop-filter: blur(24px) saturate(200%);
  border: var(--lg-border);
  box-shadow: var(--lg-shadow);
}

/* ===== 移动端适配 ===== */
@media (max-width: 768px) {
  .table-card {
    border-radius: 20px;
  }
}
</style>

// src/views/LogsView.tsx
import { useEffect, useState } from 'react'
import type { ColumnsType } from 'antd/es/table'
import { Card, Pagination, Table, Tag, Typography } from 'antd'
import { logs } from '@/api/logs'
import { actionLabel, actionTagColor, formatTime } from '@/utils'
import { getErrorMessage, isHandledError } from '@/api/request'
import { messageError } from '@/utils/messageBridge'
import type { OperationLog } from '@/types'

const { Text } = Typography

export default function LogsView() {
  const [list, setList] = useState<OperationLog[]>([])
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [size, setSize] = useState(20)
  const [total, setTotal] = useState(0)

  async function loadLogs(p: number, s: number = size) {
    setLoading(true)
    try {
      const data = await logs(p, s)
      setList(data.logs)
      setPage(p)
      setSize(s)
      setTotal(data.totalElements)
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadLogs(1)
  }, [])

  const totalPages = Math.max(1, Math.ceil(total / size))

  const columns: ColumnsType<OperationLog> = [
    { title: '#', width: 70, dataIndex: 'id' },
    {
      title: '操作人',
      width: 130,
      render: (_: unknown, row: OperationLog) => <Text strong>{row.username}</Text>,
    },
    {
      title: '操作',
      width: 140,
      render: (_: unknown, row: OperationLog) => (
        <Tag color={actionTagColor(row.action)}>{actionLabel(row.action)}</Tag>
      ),
    },
    {
      title: '对象',
      render: (_: unknown, row: OperationLog) =>
        row.target ? <span className="code-chip">{row.target}</span> : <Text type="secondary">—</Text>,
    },
    {
      title: '详情',
      render: (_: unknown, row: OperationLog) => <Text type="secondary">{row.detail || '—'}</Text>,
    },
    {
      title: '时间',
      width: 170,
      render: (_: unknown, row: OperationLog) => <Text type="secondary">{formatTime(row.createTime)}</Text>,
    },
  ]

  return (
    <div>
      <div className="page-header-block">
        <h2 className="page-title">操作日志</h2>
        <p className="page-subtitle">系统操作审计记录</p>
      </div>

      <Card className="table-card" styles={{ body: { padding: 24 } }} variant="outlined">
        <Table<OperationLog>
          rowKey="id"
          columns={columns}
          dataSource={list}
          loading={loading}
          bordered
          scroll={{ x: 1000 }}
          pagination={false}
        />
        {totalPages > 1 && (
          <div style={{ textAlign: 'center', marginTop: 16 }}>
            <Pagination
              current={page}
              pageSize={size}
              total={total}
              onChange={(p) => void loadLogs(p)}
              size="small"
            />
          </div>
        )}
      </Card>
    </div>
  )
}
