// src/views/MyCodesView.tsx
import { useEffect, useState } from 'react'
import type { ColumnsType } from 'antd/es/table'
import { Button, Card, Pagination, Table, Typography } from 'antd'
import { myCodes } from '@/api/codes'
import { copyText, formatTime } from '@/utils'
import { getErrorMessage, isHandledError } from '@/api/request'
import { messageError, messageSuccess, messageWarning } from '@/utils/messageBridge'
import type { ActivationCode } from '@/types'

const { Text } = Typography

export default function MyCodesView() {
  const [list, setList] = useState<ActivationCode[]>([])
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [total, setTotal] = useState(0)

  async function loadMyCodes(p: number, size: number = pageSize) {
    setLoading(true)
    try {
      const data = await myCodes(p, size)
      setList(data.codes)
      setPage(p)
      setPageSize(size)
      setTotal(data.total)
    } catch (err) {
      if (!isHandledError(err)) messageError(getErrorMessage(err))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadMyCodes(1)
  }, [])

  async function copyCode(code: string) {
    const ok = await copyText(code)
    if (ok) messageSuccess('已复制到剪贴板')
    else messageWarning('复制失败，请手动复制')
  }

  const columns: ColumnsType<ActivationCode> = [
    {
      title: '#',
      width: 64,
      align: 'center',
      // 跨页连续序号：第 2 页从上一页结束编号继续（如每页 20 条，则第 2 页从 21 开始）
      render: (_: unknown, __: ActivationCode, index: number) => (page - 1) * pageSize + index + 1,
    },
    {
      title: '激活码',
      dataIndex: 'code',
      render: (value: string) => <span className="code-chip">{value}</span>,
    },
    {
      title: '获取时间',
      width: 180,
      render: (_: unknown, row: ActivationCode) => <Text type="secondary">{formatTime(row.fetchTime)}</Text>,
    },
    {
      title: '操作',
      width: 100,
      render: (_: unknown, row: ActivationCode) => (
        <Button size="small" type="default" onClick={() => void copyCode(row.code)}>
          复制
        </Button>
      ),
    },
  ]

  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  return (
    <div>
      <div className="page-header-block">
        <h2 className="page-title">我的获取记录</h2>
        <p className="page-subtitle">查看您获取过的激活码</p>
      </div>

      <Card className="table-card" styles={{ body: { padding: 24 } }} variant="outlined">
        <Table<ActivationCode>
          rowKey="id"
          columns={columns}
          dataSource={list}
          loading={loading}
          bordered
          scroll={{ x: 600 }}
          pagination={false}
        />
        {totalPages > 1 && (
          <div style={{ textAlign: 'center', marginTop: 16 }}>
            <Pagination
              current={page}
              pageSize={pageSize}
              total={total}
              onChange={(p) => void loadMyCodes(p)}
              size="small"
            />
          </div>
        )}
      </Card>
    </div>
  )
}

// src/views/MyCodesView.vue
<script setup lang="ts">
import { h, ref, reactive, onMounted } from 'vue'
import { NButton, type DataTableColumns } from 'naive-ui'
import { myCodes } from '@/api/codes'
import { useUtils } from '@/composables/useUtils'
import { getErrorMessage, isHandledError } from '@/api/request'
import type { ActivationCode } from '@/types'

const { message, formatTime, copyToClipboard } = useUtils()

const myCodesList = ref<ActivationCode[]>([])
const loading = ref(false)

const pagination = reactive({
  page: 1,
  pageSize: 20,
  itemCount: 0,
  showSizePicker: true,
  pageSizes: [10, 20, 50, 100],
  onUpdatePage: (page: number) => loadMyCodes(page),
  onUpdatePageSize: (size: number) => {
    pagination.pageSize = size
    loadMyCodes(1)
  },
})

async function loadMyCodes(page: number) {
  loading.value = true
  try {
    const data = await myCodes(page, pagination.pageSize)
    myCodesList.value = data.codes
    pagination.page = page
    pagination.itemCount = data.total
  } catch (err) {
    if (!isHandledError(err)) message.error(getErrorMessage(err))
  } finally {
    loading.value = false
  }
}

onMounted(() => loadMyCodes(1))

const columns: DataTableColumns<ActivationCode> = [
  {
    title: '激活码',
    key: 'code',
    width: 260,
    render: (row: ActivationCode) => h('span', { class: 'code-chip' }, row.code),
  },
  {
    title: '获取时间',
    key: 'fetchTime',
    width: 180,
    render: (row: ActivationCode) =>
      h('span', { style: 'color:#64748b; font-size:13px; white-space:nowrap;' }, formatTime(row.fetchTime)),
  },
  {
    title: '操作',
    key: 'actions',
    width: 100,
    align: 'center' as const,
    render: (row: ActivationCode) =>
      h(
        NButton,
        { size: 'small', style: 'min-width:56px;', onClick: () => copyToClipboard(row.code) },
        { default: () => '复制' },
      ),
  },
]
</script>

<template>
  <div>
    <div class="page-header-block">
      <h2 class="page-title">我的获取记录</h2>
      <p class="page-subtitle">查看您获取过的激活码</p>
    </div>

    <n-card :bordered="false" class="table-card">
      <n-spin :show="loading">
        <n-data-table
          remote
          :columns="columns"
          :data="myCodesList"
          :pagination="pagination"
          :bordered="false"
          :single-line="false"
          :scroll-x="540"
        >
          <template #empty>
            <n-empty description="暂无获取记录" />
          </template>
        </n-data-table>
      </n-spin>
    </n-card>
  </div>
</template>

<style scoped>
.table-card {
  border-radius: 18px;
  overflow: hidden;
  background: var(--lg-bg) !important;
  backdrop-filter: blur(24px) saturate(200%);
  -webkit-backdrop-filter: blur(24px) saturate(200%);
  border: var(--lg-border);
  box-shadow: var(--lg-shadow);
}

/* ===== 移动端适配 ===== */
@media (max-width: 768px) {
  .table-card {
    border-radius: 20px;
  }
}
</style>
